CREATE USER ecs_admin WITH PASSWORD 'f4$Fb1;*5/qR4%Xj)A@T';

CREATE DATABASE ecs_admin_dev_1 OWNER ecs_admin;

SET ROLE ecs_admin;

SELECT current_user;

CREATE TABLE Menu
(
    id         BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type       INT          NOT NULL,
    parentId   BIGINT       NOT NULL,
    name       VARCHAR(32)  NOT NULL,
    icon       VARCHAR(128) NOT NULL DEFAULT '',
    path       VARCHAR(255) NOT NULL,
    sortBy     INT          NOT NULL,
    state      INT          NOT NULL,
    remark     TEXT         NOT NULL,
    createBy   VARCHAR(32)  NOT NULL,
    createTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateBy   VARCHAR(32)  NOT NULL DEFAULT '',
    updateTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE Menu IS '角色菜单表';
COMMENT ON COLUMN Menu.type IS '类型: 1.目录, 2.菜单, 3.接口';
COMMENT ON COLUMN Menu.parentId IS '父级ID';
COMMENT ON COLUMN Menu.name IS '名称';
COMMENT ON COLUMN Menu.icon IS '图标';
COMMENT ON COLUMN Menu.path IS '路径';
COMMENT ON COLUMN Menu.sortBy IS '排序';
COMMENT ON COLUMN Menu.state IS '状态, 0: 禁用, 1: 启用';
COMMENT ON COLUMN Menu.remark IS '备注';
COMMENT ON COLUMN Menu.createBy IS '操作人员';
COMMENT ON COLUMN Menu.createTime IS '创建时间';
COMMENT ON COLUMN Menu.updateBy IS '操作人员';
COMMENT ON COLUMN Menu.updateTime IS '更新时间';

INSERT INTO Menu (id, type, parentId, name, icon, path, sortBy, state, remark, createBy)
VALUES (1, 1, 0, ' 菜单管理 ', ' Menu ', '', 2001, 1, ' 菜单管理 ', ' admin '),
       (2, 2, 1, ' 菜单列表 ', ' Menu ', '/menu/ index ', 1, 1, ' 菜单列表 ', ' admin '),
       (3, 3, 2, ' 菜单查询 ', '', '/menu/ query ', 1, 1, ' 菜单查询 ', ' admin '),
       (4, 3, 2, ' 菜单添加 ', '', '/menu/ add ', 2, 1, ' 菜单添加 ', ' admin '),
       (5, 3, 2, ' 菜单修改 ', '', '/menu/ update ', 3, 1, ' 菜单修改 ', ' admin '),
       (6, 3, 2, ' 菜单状态更改 ', '', '/menu/change/state ', 4, 1, ' 菜单状态更改 ', ' admin '),
       (7, 3, 2, ' 菜单删除 ', '', '/menu/ delete ', 5, 1, ' 菜单删除 ', ' admin '),
       (8, 1, 0, ' 管理员 ', ' Avatar ', '', 2002, 1, ' 管理员 ', ' admin '),
       (9, 2, 8, ' 角色列表 ', ' Avatar ', '/ admin / role / index ', 1, 1, ' 角色列表 ', ' admin '),
       (10, 3, 9, ' 角色查询 ', '', '/ admin / role / query ', 1, 1, ' 角色查询 ', ' admin '),
       (11, 3, 9, ' 角色添加 ', '', '/ admin / role / add ', 2, 1, ' 角色添加 ', ' admin '),
       (12, 3, 9, ' 角色修改 ', '', '/ admin / role / update ', 3, 1, ' 角色修改 ', ' admin '),
       (13, 3, 9, ' 角色状态更改 ', '', '/ admin / role /change/state ', 4, 1, ' 角色状态更改 ', ' admin '),
       (14, 3, 9, ' 角色删除 ', '', '/ admin / role / delete ', 5, 1, ' 角色删除 ', ' admin '),
       (15, 3, 9, ' 角色菜单查询 ', '', '/ admin / role /menu/ query ', 6, 1, ' 角色菜单查询 ', ' admin '),
       (16, 3, 9, ' 角色菜单设置 ', '', '/ admin / role /menu/ set ', 7, 1, ' 角色菜单设置 ', ' admin '),
       (17, 2, 8, ' 管理员列表 ', ' UserFilled ', '/ admin / index ', 2, 1, ' 管理员列表 ', ' admin '),
       (18, 3, 17, ' 管理员查询 ', '', '/ admin / query ', 1, 1, ' 管理员查询 ', ' admin '),
       (19, 3, 17, ' 管理员添加 ', '', '/ admin / add ', 2, 1, ' 管理员添加 ', ' admin '),
       (20, 3, 17, ' 管理员修改 ', '', '/ admin / update ', 3, 1, ' 管理员修改 ', ' admin '),
       (21, 3, 17, ' 管理员状态更改 ', '', '/ admin /change/state ', 6, 1, ' 管理员状态更改 ', ' admin '),
       (22, 3, 17, ' 管理员删除 ', '', '/ admin / delete ', 7, 1, ' 管理员删除 ', ' admin '),
       (23, 1, 0, ' 设置 ', ' Setting ', '', 2003, 1, ' 设置 ', ' admin '),
       (24, 2, 23, ' 详细信息 ', ' User ', '/setting/ detail ', 1, 1, ' 详细信息 ', ' admin '),
       (25, 3, 24, ' 修改信息 ', '', '/setting/change/ detail ', 1, 1, ' 更新信息 ', ' admin '),
       (26, 2, 23, ' 修改密码 ', ' Lock ', '/setting/change/ password ', 2, 1, ' 修改密码 ', ' admin '),
       (27, 3, 26, ' 修改密码 ', '', '/setting/change/ Password ', 2, 1, ' 更新信息 ', ' admin ');

CREATE TABLE Role
(
    id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(32) NOT NULL,
    state      INT         NOT NULL,
    remark     TEXT        NOT NULL,
    createBy   VARCHAR(32) NOT NULL,
    createTime TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateBy   VARCHAR(32) NOT NULL DEFAULT '',
    updateTime TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE Role IS '管理员角色表';
COMMENT ON COLUMN Role.name IS ' 名称 ';
COMMENT ON COLUMN Role.state IS ' 状态, 0: 禁用, 1: 启用 ';
COMMENT ON COLUMN Role.remark IS ' 备注 ';
COMMENT ON COLUMN Role.createBy IS ' 操作人员 ';
COMMENT ON COLUMN Role.createTime IS ' 创建时间 ';
COMMENT ON COLUMN Role.updateBy IS ' 操作人员 ';
COMMENT ON COLUMN Role.updateTime IS ' 更新时间 ';

INSERT INTO Role (id, name, state, remark, createBy)
VALUES (1, ' 管理员 ', 1, ' 管理员 ', ' system ');

CREATE TABLE RoleMenuRelation
(
    id     BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    roleId BIGINT NOT NULL,
    menuId BIGINT NOT NULL,
    UNIQUE (roleId, menuId)
);

COMMENT ON TABLE RoleMenuRelation IS ' 角色菜单表 ';
COMMENT ON COLUMN RoleMenuRelation.roleId IS ' 角色ID ';
COMMENT ON COLUMN RoleMenuRelation.menuId IS ' 菜单ID ';

INSERT INTO RoleMenuRelation(roleId, menuId)
SELECT 1, id
FROM Menu;

CREATE TABLE Admin
(
    id         BIGINT       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    roleId     BIGINT       NOT NULL,
    username   VARCHAR(32)  NOT NULL,
    password   VARCHAR(128) NOT NULL,
    nickname   VARCHAR(32)  NOT NULL,
    avatar     varchar(255) NOT NULL,
    email      VARCHAR(64)  NOT NULL DEFAULT '',
    mobile     VARCHAR(32)  NOT NULL DEFAULT '',
    state      INT          NOT NULL,
    remark     TEXT         NOT NULL,
    createBy   VARCHAR(32)  NOT NULL,
    createTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateBy   VARCHAR(32)  NOT NULL DEFAULT '',
    updateTime TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE Admin IS ' 管理员表 ';

COMMENT ON COLUMN Admin.roleId IS '角色ID';
COMMENT ON COLUMN Admin.username IS '用户名';
COMMENT ON COLUMN Admin.password IS '密码';
COMMENT ON COLUMN Admin.nickname IS '昵称';
COMMENT ON COLUMN Admin.avatar IS '头像';
COMMENT ON COLUMN Admin.email IS '邮箱';
COMMENT ON COLUMN Admin.mobile IS '手机号';
COMMENT ON COLUMN Admin.state IS '状态, 0: 禁用, 1: 启用';
COMMENT ON COLUMN Admin.remark IS '备注';
COMMENT ON COLUMN Admin.createBy IS '操作人';
COMMENT ON COLUMN Admin.createTime IS '创建时间';
COMMENT ON COLUMN Admin.updateBy IS '操作人员 ';
COMMENT ON COLUMN Admin.updateTime IS '更新时间';

INSERT INTO Admin (id, roleId, username, password, nickname, avatar, email, mobile, state, remark, createBy)
VALUES (1, 1, ' admin ', '$100801$ZK+purVNYumxYMoxPQTIMg==$Yp1s1fVJlViJM/6p7biowp147eCfCqLj0FsGc1AeWqU=', '管理员',
        'avatar7.png', '', '', 1, '管理员', 'system');
